/* @page reg.c
 *       Registers
 *       2022
 */

#include "reg.h"


/** @brief  Init. registers.
 *  @param  None.
 *  @return The number of inited registers.
 */
uint16_t REG_Init(void)
{
    uint16_t Res = 0;

    //clear register memory
    REG_Clear();

    //DI
    Res += REG_InitRegs(REG_DI_NORM_VAL__GID, REG_DI_NORM_VAL__ZONE, REG_DI_NORM_VAL__TYPESZ, REG_DI_NORM_VAL__GROUP, REG_DI_NORM_VAL__TYPE, REG_DI_NORM_VAL__POS, REG_DI_NORM_VAL__SZ, REG_DI_NORM_VAL__SADDR, REG_DI_NORM_VAL__MBTABLE, REG_DI_NORM_VAL__MBPOS, REG_DI_NORM_VAL__A00, REG_DI_NORM_VAL__A01, REG_DI_NORM_VAL__A02, REG_DI_NORM_VAL__DTABLE, REG_DI_NORM_VAL__DPOS, REG_DI_NORM_VAL__EAREA, REG_DI_NORM_VAL__EPOS);
    Res += REG_InitRegs(REG_DI_TACH_VAL__GID, REG_DI_TACH_VAL__ZONE, REG_DI_TACH_VAL__TYPESZ, REG_DI_TACH_VAL__GROUP, REG_DI_TACH_VAL__TYPE, REG_DI_TACH_VAL__POS, REG_DI_TACH_VAL__SZ, REG_DI_TACH_VAL__SADDR, REG_DI_TACH_VAL__MBTABLE, REG_DI_TACH_VAL__MBPOS, REG_DI_TACH_VAL__A00, REG_DI_TACH_VAL__A01, REG_DI_TACH_VAL__A02, REG_DI_TACH_VAL__DTABLE, REG_DI_TACH_VAL__DPOS, REG_DI_TACH_VAL__EAREA, REG_DI_TACH_VAL__EPOS);
    Res += REG_InitRegs(REG_DI_TACH_SETPOINT__GID, REG_DI_TACH_SETPOINT__ZONE, REG_DI_TACH_SETPOINT__TYPESZ, REG_DI_TACH_SETPOINT__GROUP, REG_DI_TACH_SETPOINT__TYPE, REG_DI_TACH_SETPOINT__POS, REG_DI_TACH_SETPOINT__SZ, REG_DI_TACH_SETPOINT__SADDR, REG_DI_TACH_SETPOINT__MBTABLE, REG_DI_TACH_SETPOINT__MBPOS, REG_DI_TACH_SETPOINT__A00, REG_DI_TACH_SETPOINT__A01, REG_DI_TACH_SETPOINT__A02, REG_DI_TACH_SETPOINT__DTABLE, REG_DI_TACH_SETPOINT__DPOS, REG_DI_TACH_SETPOINT__EAREA, REG_DI_TACH_SETPOINT__EPOS);
    Res += REG_InitRegs(REG_DI_TACH_SETPOINT_RES__GID, REG_DI_TACH_SETPOINT_RES__ZONE, REG_DI_TACH_SETPOINT_RES__TYPESZ, REG_DI_TACH_SETPOINT_RES__GROUP, REG_DI_TACH_SETPOINT_RES__TYPE, REG_DI_TACH_SETPOINT_RES__POS, REG_DI_TACH_SETPOINT_RES__SZ, REG_DI_TACH_SETPOINT_RES__SADDR, REG_DI_TACH_SETPOINT_RES__MBTABLE, REG_DI_TACH_SETPOINT_RES__MBPOS, REG_DI_TACH_SETPOINT_RES__A00, REG_DI_TACH_SETPOINT_RES__A01, REG_DI_TACH_SETPOINT_RES__A02, REG_DI_TACH_SETPOINT_RES__DTABLE, REG_DI_TACH_SETPOINT_RES__DPOS, REG_DI_TACH_SETPOINT_RES__EAREA, REG_DI_TACH_SETPOINT_RES__EPOS);
    Res += REG_InitRegs(REG_DI_TACH_SETPOINT_ALLOW__GID, REG_DI_TACH_SETPOINT_ALLOW__ZONE, REG_DI_TACH_SETPOINT_ALLOW__TYPESZ, REG_DI_TACH_SETPOINT_ALLOW__GROUP, REG_DI_TACH_SETPOINT_ALLOW__TYPE, REG_DI_TACH_SETPOINT_ALLOW__POS, REG_DI_TACH_SETPOINT_ALLOW__SZ, REG_DI_TACH_SETPOINT_ALLOW__SADDR, REG_DI_TACH_SETPOINT_ALLOW__MBTABLE, REG_DI_TACH_SETPOINT_ALLOW__MBPOS, REG_DI_TACH_SETPOINT_ALLOW__A00, REG_DI_TACH_SETPOINT_ALLOW__A01, REG_DI_TACH_SETPOINT_ALLOW__A02, REG_DI_TACH_SETPOINT_ALLOW__DTABLE, REG_DI_TACH_SETPOINT_ALLOW__DPOS, REG_DI_TACH_SETPOINT_ALLOW__EAREA, REG_DI_TACH_SETPOINT_ALLOW__EPOS);
    Res += REG_InitRegs(REG_DI_CNTR_VAL__GID, REG_DI_CNTR_VAL__ZONE, REG_DI_CNTR_VAL__TYPESZ, REG_DI_CNTR_VAL__GROUP, REG_DI_CNTR_VAL__TYPE, REG_DI_CNTR_VAL__POS, REG_DI_CNTR_VAL__SZ, REG_DI_CNTR_VAL__SADDR, REG_DI_CNTR_VAL__MBTABLE, REG_DI_CNTR_VAL__MBPOS, REG_DI_CNTR_VAL__A00, REG_DI_CNTR_VAL__A01, REG_DI_CNTR_VAL__A02, REG_DI_CNTR_VAL__DTABLE, REG_DI_CNTR_VAL__DPOS, REG_DI_CNTR_VAL__EAREA, REG_DI_CNTR_VAL__EPOS);
    Res += REG_InitRegs(REG_DI_CNTR_SETPOINT__GID, REG_DI_CNTR_SETPOINT__ZONE, REG_DI_CNTR_SETPOINT__TYPESZ, REG_DI_CNTR_SETPOINT__GROUP, REG_DI_CNTR_SETPOINT__TYPE, REG_DI_CNTR_SETPOINT__POS, REG_DI_CNTR_SETPOINT__SZ, REG_DI_CNTR_SETPOINT__SADDR, REG_DI_CNTR_SETPOINT__MBTABLE, REG_DI_CNTR_SETPOINT__MBPOS, REG_DI_CNTR_SETPOINT__A00, REG_DI_CNTR_SETPOINT__A01, REG_DI_CNTR_SETPOINT__A02, REG_DI_CNTR_SETPOINT__DTABLE, REG_DI_CNTR_SETPOINT__DPOS, REG_DI_CNTR_SETPOINT__EAREA, REG_DI_CNTR_SETPOINT__EPOS);
    Res += REG_InitRegs(REG_DI_CNTR_SETPOINT_RES__GID, REG_DI_CNTR_SETPOINT_RES__ZONE, REG_DI_CNTR_SETPOINT_RES__TYPESZ, REG_DI_CNTR_SETPOINT_RES__GROUP, REG_DI_CNTR_SETPOINT_RES__TYPE, REG_DI_CNTR_SETPOINT_RES__POS, REG_DI_CNTR_SETPOINT_RES__SZ, REG_DI_CNTR_SETPOINT_RES__SADDR, REG_DI_CNTR_SETPOINT_RES__MBTABLE, REG_DI_CNTR_SETPOINT_RES__MBPOS, REG_DI_CNTR_SETPOINT_RES__A00, REG_DI_CNTR_SETPOINT_RES__A01, REG_DI_CNTR_SETPOINT_RES__A02, REG_DI_CNTR_SETPOINT_RES__DTABLE, REG_DI_CNTR_SETPOINT_RES__DPOS, REG_DI_CNTR_SETPOINT_RES__EAREA, REG_DI_CNTR_SETPOINT_RES__EPOS);
    Res += REG_InitRegs(REG_DI_CNTR_SETPOINT_ALLOW__GID, REG_DI_CNTR_SETPOINT_ALLOW__ZONE, REG_DI_CNTR_SETPOINT_ALLOW__TYPESZ, REG_DI_CNTR_SETPOINT_ALLOW__GROUP, REG_DI_CNTR_SETPOINT_ALLOW__TYPE, REG_DI_CNTR_SETPOINT_ALLOW__POS, REG_DI_CNTR_SETPOINT_ALLOW__SZ, REG_DI_CNTR_SETPOINT_ALLOW__SADDR, REG_DI_CNTR_SETPOINT_ALLOW__MBTABLE, REG_DI_CNTR_SETPOINT_ALLOW__MBPOS, REG_DI_CNTR_SETPOINT_ALLOW__A00, REG_DI_CNTR_SETPOINT_ALLOW__A01, REG_DI_CNTR_SETPOINT_ALLOW__A02, REG_DI_CNTR_SETPOINT_ALLOW__DTABLE, REG_DI_CNTR_SETPOINT_ALLOW__DPOS, REG_DI_CNTR_SETPOINT_ALLOW__EAREA, REG_DI_CNTR_SETPOINT_ALLOW__EPOS);
    Res += REG_InitRegs(REG_DI_MODE__GID, REG_DI_MODE__ZONE, REG_DI_MODE__TYPESZ, REG_DI_MODE__GROUP, REG_DI_MODE__TYPE, REG_DI_MODE__POS, REG_DI_MODE__SZ, REG_DI_MODE__SADDR, REG_DI_MODE__MBTABLE, REG_DI_MODE__MBPOS, REG_DI_MODE__A00, REG_DI_MODE__A01, REG_DI_MODE__A02, REG_DI_MODE__DTABLE, REG_DI_MODE__DPOS, REG_DI_MODE__EAREA, REG_DI_MODE__EPOS);
    Res += REG_InitRegs(REG_DI_RESET__GID, REG_DI_RESET__ZONE, REG_DI_RESET__TYPESZ, REG_DI_RESET__GROUP, REG_DI_RESET__TYPE, REG_DI_RESET__POS, REG_DI_RESET__SZ, REG_DI_RESET__SADDR, REG_DI_RESET__MBTABLE, REG_DI_RESET__MBPOS, REG_DI_RESET__A00, REG_DI_RESET__A01, REG_DI_RESET__A02, REG_DI_RESET__DTABLE, REG_DI_RESET__DPOS, REG_DI_RESET__EAREA, REG_DI_RESET__EPOS);

    //DO
    Res += REG_InitRegs(REG_DO_NORM_VAL__GID, REG_DO_NORM_VAL__ZONE, REG_DO_NORM_VAL__TYPESZ, REG_DO_NORM_VAL__GROUP, REG_DO_NORM_VAL__TYPE, REG_DO_NORM_VAL__POS, REG_DO_NORM_VAL__SZ, REG_DO_NORM_VAL__SADDR, REG_DO_NORM_VAL__MBTABLE, REG_DO_NORM_VAL__MBPOS, REG_DO_NORM_VAL__A00, REG_DO_NORM_VAL__A01, REG_DO_NORM_VAL__A02, REG_DO_NORM_VAL__DTABLE, REG_DO_NORM_VAL__DPOS, REG_DO_NORM_VAL__EAREA, REG_DO_NORM_VAL__EPOS);
    Res += REG_InitRegs(REG_DO_FAST_VAL__GID, REG_DO_FAST_VAL__ZONE, REG_DO_FAST_VAL__TYPESZ, REG_DO_FAST_VAL__GROUP, REG_DO_FAST_VAL__TYPE, REG_DO_FAST_VAL__POS, REG_DO_FAST_VAL__SZ, REG_DO_FAST_VAL__SADDR, REG_DO_FAST_VAL__MBTABLE, REG_DO_FAST_VAL__MBPOS, REG_DO_FAST_VAL__A00, REG_DO_FAST_VAL__A01, REG_DO_FAST_VAL__A02, REG_DO_FAST_VAL__DTABLE, REG_DO_FAST_VAL__DPOS, REG_DO_FAST_VAL__EAREA, REG_DO_FAST_VAL__EPOS);
    Res += REG_InitRegs(REG_DO_PWM_VAL__GID, REG_DO_PWM_VAL__ZONE, REG_DO_PWM_VAL__TYPESZ, REG_DO_PWM_VAL__GROUP, REG_DO_PWM_VAL__TYPE, REG_DO_PWM_VAL__POS, REG_DO_PWM_VAL__SZ, REG_DO_PWM_VAL__SADDR, REG_DO_PWM_VAL__MBTABLE, REG_DO_PWM_VAL__MBPOS, REG_DO_PWM_VAL__A00, REG_DO_PWM_VAL__A01, REG_DO_PWM_VAL__A02, REG_DO_PWM_VAL__DTABLE, REG_DO_PWM_VAL__DPOS, REG_DO_PWM_VAL__EAREA, REG_DO_PWM_VAL__EPOS);
    Res += REG_InitRegs(REG_DO_PWM_ALLOW__GID, REG_DO_PWM_ALLOW__ZONE, REG_DO_PWM_ALLOW__TYPESZ, REG_DO_PWM_ALLOW__GROUP, REG_DO_PWM_ALLOW__TYPE, REG_DO_PWM_ALLOW__POS, REG_DO_PWM_ALLOW__SZ, REG_DO_PWM_ALLOW__SADDR, REG_DO_PWM_ALLOW__MBTABLE, REG_DO_PWM_ALLOW__MBPOS, REG_DO_PWM_ALLOW__A00, REG_DO_PWM_ALLOW__A01, REG_DO_PWM_ALLOW__A02, REG_DO_PWM_ALLOW__DTABLE, REG_DO_PWM_ALLOW__DPOS, REG_DO_PWM_ALLOW__EAREA, REG_DO_PWM_ALLOW__EPOS);
    Res += REG_InitRegs(REG_DO_PWM_PERIOD__GID, REG_DO_PWM_PERIOD__ZONE, REG_DO_PWM_PERIOD__TYPESZ, REG_DO_PWM_PERIOD__GROUP, REG_DO_PWM_PERIOD__TYPE, REG_DO_PWM_PERIOD__POS, REG_DO_PWM_PERIOD__SZ, REG_DO_PWM_PERIOD__SADDR, REG_DO_PWM_PERIOD__MBTABLE, REG_DO_PWM_PERIOD__MBPOS, REG_DO_PWM_PERIOD__A00, REG_DO_PWM_PERIOD__A01, REG_DO_PWM_PERIOD__A02, REG_DO_PWM_PERIOD__DTABLE, REG_DO_PWM_PERIOD__DPOS, REG_DO_PWM_PERIOD__EAREA, REG_DO_PWM_PERIOD__EPOS);
    Res += REG_InitRegs(REG_DO_MODE__GID, REG_DO_MODE__ZONE, REG_DO_MODE__TYPESZ, REG_DO_MODE__GROUP, REG_DO_MODE__TYPE, REG_DO_MODE__POS, REG_DO_MODE__SZ, REG_DO_MODE__SADDR, REG_DO_MODE__MBTABLE, REG_DO_MODE__MBPOS, REG_DO_MODE__A00, REG_DO_MODE__A01, REG_DO_MODE__A02, REG_DO_MODE__DTABLE, REG_DO_MODE__DPOS, REG_DO_MODE__EAREA, REG_DO_MODE__EPOS);
    Res += REG_InitRegs(REG_DO_SAFE_ALLOW__GID, REG_DO_SAFE_ALLOW__ZONE, REG_DO_SAFE_ALLOW__TYPESZ, REG_DO_SAFE_ALLOW__GROUP, REG_DO_SAFE_ALLOW__TYPE, REG_DO_SAFE_ALLOW__POS, REG_DO_SAFE_ALLOW__SZ, REG_DO_SAFE_ALLOW__SADDR, REG_DO_SAFE_ALLOW__MBTABLE, REG_DO_SAFE_ALLOW__MBPOS, REG_DO_SAFE_ALLOW__A00, REG_DO_SAFE_ALLOW__A01, REG_DO_SAFE_ALLOW__A02, REG_DO_SAFE_ALLOW__DTABLE, REG_DO_SAFE_ALLOW__DPOS, REG_DO_SAFE_ALLOW__EAREA, REG_DO_SAFE_ALLOW__EPOS);
    Res += REG_InitRegs(REG_DO_SAFE_VAL__GID, REG_DO_SAFE_VAL__ZONE, REG_DO_SAFE_VAL__TYPESZ, REG_DO_SAFE_VAL__GROUP, REG_DO_SAFE_VAL__TYPE, REG_DO_SAFE_VAL__POS, REG_DO_SAFE_VAL__SZ, REG_DO_SAFE_VAL__SADDR, REG_DO_SAFE_VAL__MBTABLE, REG_DO_SAFE_VAL__MBPOS, REG_DO_SAFE_VAL__A00, REG_DO_SAFE_VAL__A01, REG_DO_SAFE_VAL__A02, REG_DO_SAFE_VAL__DTABLE, REG_DO_SAFE_VAL__DPOS, REG_DO_SAFE_VAL__EAREA, REG_DO_SAFE_VAL__EPOS);

    //SYS_STAT
    Res += REG_InitRegs(REG_SYS_STAT__GID, REG_SYS_STAT__ZONE, REG_SYS_STAT__TYPESZ, REG_SYS_STAT__GROUP, REG_SYS_STAT__TYPE, REG_SYS_STAT__POS, REG_SYS_STAT__SZ, REG_SYS_STAT__SADDR, REG_SYS_STAT__MBTABLE, REG_SYS_STAT__MBPOS, REG_SYS_STAT__A00, REG_SYS_STAT__A01, REG_SYS_STAT__A02, REG_SYS_STAT__DTABLE, REG_SYS_STAT__DPOS, REG_SYS_STAT__EAREA, REG_SYS_STAT__EPOS);

    //USER_DATA
    Res += REG_InitRegs(REG_USER_DATA1__GID, REG_USER_DATA1__ZONE, REG_USER_DATA1__TYPESZ, REG_USER_DATA1__GROUP, REG_USER_DATA1__TYPE, REG_USER_DATA1__POS, REG_USER_DATA1__SZ, REG_USER_DATA1__SADDR, REG_USER_DATA1__MBTABLE, REG_USER_DATA1__MBPOS, REG_USER_DATA1__A00, REG_USER_DATA1__A01, REG_USER_DATA1__A02, REG_USER_DATA1__DTABLE, REG_USER_DATA1__DPOS, REG_USER_DATA1__EAREA, REG_USER_DATA1__EPOS);
    Res += REG_InitRegs(REG_USER_DATA2__GID, REG_USER_DATA2__ZONE, REG_USER_DATA2__TYPESZ, REG_USER_DATA2__GROUP, REG_USER_DATA2__TYPE, REG_USER_DATA2__POS, REG_USER_DATA2__SZ, REG_USER_DATA2__SADDR, REG_USER_DATA2__MBTABLE, REG_USER_DATA2__MBPOS, REG_USER_DATA2__A00, REG_USER_DATA2__A01, REG_USER_DATA2__A02, REG_USER_DATA2__DTABLE, REG_USER_DATA2__DPOS, REG_USER_DATA2__EAREA, REG_USER_DATA2__EPOS);

#ifdef DEBUG_REG
    DebugLog("MbTables: C=%d-%d D=%d-%d H=%d-%d I=%d-%d\n", MBRTU_COIL_START, MBRTU_COIL_END, MBRTU_DISC_START, MBRTU_DISC_END, MBRTU_HOLD_START, MBRTU_HOLD_END, MBRTU_INPT_START, MBRTU_INPT_END);
#endif // DEBUG_REG

    return (Res);
}

#ifdef RTE_MOD_APP
/** @brief  Copy from Data Tables into Located variables.
 *  @param  None.
 *  @return The number of copied registers.
 */
uint16_t REG_CopyMbToApp(void)
{
    uint16_t Res = 0;

    Res += REG_CopyRegs(REG_DI_NORM_VAL__POS, REG_DI_NORM_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_CNTR_VAL__POS, REG_DI_CNTR_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_CNTR_SETPOINT__POS, REG_DI_CNTR_SETPOINT__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_CNTR_SETPOINT_RES__POS, REG_DI_CNTR_SETPOINT_RES__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_TACH_VAL__POS, REG_DI_TACH_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_TACH_SETPOINT__POS, REG_DI_TACH_SETPOINT__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_TACH_SETPOINT_RES__POS, REG_DI_TACH_SETPOINT_RES__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_MODE__POS, REG_DI_MODE__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DI_RESET__POS, REG_DI_RESET__SZ, REG_COPY_MB_TO_APP, 0);

    Res += REG_CopyRegs(REG_DO_NORM_VAL__POS, REG_DO_NORM_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_FAST_VAL__POS, REG_DO_FAST_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_PWM_VAL__POS, REG_DO_PWM_VAL__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_PWM_ALLOW__POS, REG_DO_PWM_ALLOW__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_PWM_PERIOD__POS, REG_DO_PWM_PERIOD__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_MODE__POS, REG_DO_MODE__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_SAFE_ALLOW__POS, REG_DO_SAFE_ALLOW__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_DO_SAFE_VAL__POS, REG_DO_SAFE_VAL__SZ, REG_COPY_MB_TO_APP, 0);

    Res += REG_CopyRegs(REG_USER_DATA1__POS, REG_USER_DATA1__SZ, REG_COPY_MB_TO_APP, 0);
    Res += REG_CopyRegs(REG_USER_DATA2__POS, REG_USER_DATA2__SZ, REG_COPY_MB_TO_APP, 0);

    return (Res);
}

/** @brief  Copy from Located variables into Data Tables.
 *  @param  None.
 *  @return The number of copied registers.
 */
uint16_t REG_CopyAppToMb(void)
{
    uint16_t Res = 0;

    Res += REG_CopyRegs(REG_DI_CNTR_SETPOINT__POS, REG_DI_CNTR_SETPOINT__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DI_TACH_SETPOINT__POS, REG_DI_TACH_SETPOINT__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DI_MODE__POS, REG_DI_MODE__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DI_RESET__POS, REG_DI_RESET__SZ, REG_COPY_APP_TO_MB, 0);

    Res += REG_CopyRegs(REG_DO_NORM_VAL__POS, REG_DO_NORM_VAL__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_FAST_VAL__POS, REG_DO_FAST_VAL__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_PWM_VAL__POS, REG_DO_PWM_VAL__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_PWM_ALLOW__POS, REG_DO_PWM_ALLOW__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_PWM_PERIOD__POS, REG_DO_PWM_PERIOD__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_MODE__POS, REG_DO_MODE__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_SAFE_ALLOW__POS, REG_DO_SAFE_ALLOW__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_DO_SAFE_VAL__POS, REG_DO_SAFE_VAL__SZ, REG_COPY_APP_TO_MB, 0);

    Res += REG_CopyRegs(REG_USER_DATA1__POS, REG_USER_DATA1__SZ, REG_COPY_APP_TO_MB, 0);
    Res += REG_CopyRegs(REG_USER_DATA2__POS, REG_USER_DATA2__SZ, REG_COPY_APP_TO_MB, 0);

    return (Res);
}
#endif // RTE_MOD_APP


/** @brief  Set values by default.
 *  @param  None.
 *  @return None.
 */
void REG_SetDef(void)
{
    uint8_t  BuffBy;
    uint16_t BuffWo;
    uint32_t BuffDwo;
    //float    BuffFlo;
    uint8_t  i;

    //DI ======================================================================
    for(i=0; i<PLC_DI_SZ; i++)
    {
        BuffBy = PLC_DI_MODE_DEF;
        REG_CopyRegByPos(REG_DI_MODE__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffBy = PLC_DI_TACH_SETPOINT_ALLOW_DEF;
        REG_CopyRegByPos(REG_DI_TACH_SETPOINT_ALLOW__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffBy = PLC_DI_CNTR_SETPOINT_ALLOW_DEF;
        REG_CopyRegByPos(REG_DI_CNTR_SETPOINT_ALLOW__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);
    }

    //DO ======================================================================
    for(i=0; i<PLC_DO_SZ; i++)
    {
        BuffBy = PLC_DO_MODE_DEF;
        REG_CopyRegByPos(REG_DO_MODE__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffDwo = PLC_DO_PWM_PERIOD_DEF;
        REG_CopyRegByPos(REG_DO_PWM_PERIOD__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffDwo);

        BuffBy = PLC_DO_SAFE_ALLOW_DEF;
        REG_CopyRegByPos(REG_DO_SAFE_ALLOW__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);

        BuffBy = PLC_DO_SAFE_VAL_DEF;
        REG_CopyRegByPos(REG_DO_SAFE_VAL__POS+i, REG_COPY_VAR_TO_MB__NO_MON, &BuffBy);
    }

    //REG_SYS_STAT =============================================================
    BuffWo = PLC_SYS_STAT1.Data;
    REG_CopyRegByPos(REG_SYS_STAT__POS_STAT1, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);

    BuffWo = PLC_HW_CODE;
    REG_CopyRegByPos(REG_SYS_STAT__POS_HW_CODE, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);

    BuffWo = PLC_RTE_VERSION;
    REG_CopyRegByPos(REG_SYS_STAT__POS_RTE_VER, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);

    BuffWo = PLC_RTE_YYYY;
    REG_CopyRegByPos(REG_SYS_STAT__POS_RTE_YYYY, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);

    BuffWo = PLC_RTE_DDMM;
    REG_CopyRegByPos(REG_SYS_STAT__POS_RTE_DDMM, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);

    BuffWo = (uint16_t)PLC_HW_VAR;
    REG_CopyRegByPos(REG_SYS_STAT__POS_HW_VAR, REG_COPY_VAR_TO_MB__NO_MON, &BuffWo);
}
